package steam

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// Errors of the game mode adaptation.
var (
	ErrNoExecutable = errors.New("no executable was found in the package payload")
	ErrNoPayload    = errors.New("the package payload is not available")
)

// Request describes the package to adapt for the SteamOS game mode.
type Request struct {
	Home        string // user home directory
	PackageName string // pacman package name, used for the prefix directory
	Name        string // display name in the Steam library
	Comment     string
	Categories  string
	PayloadDir  string // extracted data.tar
	Exec        string // executable path inside the payload, e.g. /usr/bin/foo
	IconPath    string // icon path inside the payload, optional
}

// Result reports what the adaptation created.
type Result struct {
	Prefix       string
	Launcher     string
	Desktop      string
	Icon         string
	AppID        int32
	Accounts     []string
	SteamRunning bool
}

// Adapt installs the package into a writable prefix under the user's home
// directory and registers a launcher as a non-Steam shortcut.
//
// The SteamOS root filesystem is read-only and is reset by every system
// update, so pacman -U is not a usable installation path in game mode. A
// prefix inside $HOME survives updates and needs no privileges, and the
// gamescope session can only start programs that exist in the Steam library,
// hence the shortcut.
func Adapt(req Request) (Result, error) {
	var result Result
	if req.PayloadDir == "" {
		return result, ErrNoPayload
	}
	if info, err := os.Stat(req.PayloadDir); err != nil || !info.IsDir() {
		return result, ErrNoPayload
	}
	relativeExec := strings.TrimPrefix(filepath.Clean("/"+req.Exec), "/")
	if relativeExec == "" || relativeExec == "." {
		return result, ErrNoExecutable
	}

	result.Prefix = filepath.Join(req.Home, "Applications", req.PackageName)
	if err := deploy(req.PayloadDir, result.Prefix); err != nil {
		return result, err
	}

	binary := filepath.Join(result.Prefix, relativeExec)
	if _, err := os.Stat(binary); err != nil {
		return result, fmt.Errorf("%w: %s", ErrNoExecutable, relativeExec)
	}
	if err := os.Chmod(binary, 0o755); err != nil {
		return result, err
	}

	if req.IconPath != "" {
		if relative, err := filepath.Rel(req.PayloadDir, req.IconPath); err == nil {
			result.Icon = filepath.Join(result.Prefix, relative)
		}
	}

	launcher := filepath.Join(result.Prefix, "kuznica-launch.sh")
	if err := os.WriteFile(launcher, []byte(renderLauncher(relativeExec)), 0o755); err != nil {
		return result, err
	}
	result.Launcher = launcher

	desktopPath, err := writeDesktopEntry(req, result)
	if err != nil {
		return result, err
	}
	result.Desktop = desktopPath

	users, err := Users(req.Home)
	if err != nil {
		return result, err
	}
	shortcut := Shortcut{
		Name:     displayName(req),
		Exe:      launcher,
		StartDir: result.Prefix,
		Icon:     result.Icon,
		Tags:     []string{"KUZNICA"},
	}
	for _, user := range users {
		appID, err := AddShortcut(user, shortcut)
		if err != nil {
			return result, fmt.Errorf("profile %s: %w", user.AccountID, err)
		}
		result.AppID = appID
		result.Accounts = append(result.Accounts, user.AccountID)
	}
	result.SteamRunning = IsRunning()
	return result, nil
}

func displayName(req Request) string {
	if strings.TrimSpace(req.Name) != "" {
		return req.Name
	}
	return req.PackageName
}

// renderLauncher builds the wrapper that makes a Debian tree relocatable:
// the binary is started with the prefix prepended to the library, data and
// schema search paths.
func renderLauncher(relativeExec string) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by KUZNICA (https://sd-on.ru) for the SteamOS game mode\n")
	b.WriteString("set -e\n")
	b.WriteString(`PREFIX="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)"` + "\n")
	b.WriteString(`export PATH="$PREFIX/usr/bin:$PREFIX/usr/games:$PREFIX/usr/sbin:$PATH"` + "\n")
	b.WriteString(`export LD_LIBRARY_PATH="$PREFIX/usr/lib:$PREFIX/usr/lib64:$PREFIX/usr/lib/x86_64-linux-gnu:$PREFIX/usr/lib/aarch64-linux-gnu${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"` + "\n")
	b.WriteString(`export XDG_DATA_DIRS="$PREFIX/usr/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"` + "\n")
	b.WriteString(`if [ -d "$PREFIX/usr/share/glib-2.0/schemas" ]; then` + "\n")
	b.WriteString(`  export GSETTINGS_SCHEMA_DIR="$PREFIX/usr/share/glib-2.0/schemas"` + "\n")
	b.WriteString("fi\n")
	b.WriteString(`cd "$PREFIX"` + "\n")
	fmt.Fprintf(&b, "exec \"$PREFIX/%s\" \"$@\"\n", relativeExec)
	return b.String()
}

// writeDesktopEntry adds a launcher to the desktop session as well, so the
// program is available in both SteamOS modes.
func writeDesktopEntry(req Request, result Result) (string, error) {
	dir := filepath.Join(req.Home, ".local", "share", "applications")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	icon := result.Icon
	if icon == "" {
		icon = req.PackageName
	}
	categories := req.Categories
	if categories == "" {
		categories = "Game;"
	}
	content := fmt.Sprintf(`[Desktop Entry]
Type=Application
Name=%s
Comment=%s
Exec=%s
Icon=%s
Terminal=false
StartupNotify=true
Categories=%s
`, displayName(req), oneLine(req.Comment), result.Launcher, icon, categories)

	path := filepath.Join(dir, "kuznica-"+req.PackageName+".desktop")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// IsSteamOS reports whether КУЗНИЦА runs on SteamOS (Steam Deck and the
// desktop images), where the root filesystem is read-only.
func IsSteamOS() bool {
	data, err := os.ReadFile("/etc/os-release")
	if err != nil {
		return false
	}
	for _, line := range strings.Split(string(data), "\n") {
		id, found := strings.CutPrefix(strings.TrimSpace(line), "ID=")
		if !found {
			continue
		}
		return strings.Trim(id, `"`) == "steamos"
	}
	return false
}

// IsRunning reports whether Steam is running: it rewrites shortcuts.vdf on
// exit, so it has to be restarted for a new shortcut to appear.
func IsRunning() bool {
	entries, err := os.ReadDir("/proc")
	if err != nil {
		return false
	}
	for _, entry := range entries {
		name, err := os.ReadFile(filepath.Join("/proc", entry.Name(), "comm"))
		if err != nil {
			continue
		}
		switch strings.TrimSpace(string(name)) {
		case "steam", "steamwebhelper":
			return true
		}
	}
	return false
}

// deploy replaces the prefix with a copy of the payload.
func deploy(payload, prefix string) error {
	if err := os.RemoveAll(prefix); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(prefix), 0o755); err != nil {
		return err
	}
	return copyTree(payload, prefix)
}

func copyTree(source, target string) error {
	return filepath.Walk(source, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		relative, err := filepath.Rel(source, path)
		if err != nil {
			return err
		}
		destination := filepath.Join(target, relative)
		switch {
		case info.IsDir():
			return os.MkdirAll(destination, info.Mode().Perm()|0o700)
		case info.Mode()&os.ModeSymlink != 0:
			link, err := os.Readlink(path)
			if err != nil {
				return err
			}
			os.Remove(destination)
			return os.Symlink(link, destination)
		case info.Mode().IsRegular():
			return copyFile(path, destination, info.Mode().Perm())
		default:
			return nil // sockets, devices and fifos are not deployed
		}
	})
}

func copyFile(source, target string, mode os.FileMode) error {
	in, err := os.Open(source)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.OpenFile(target, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, mode)
	if err != nil {
		return err
	}
	if _, err := io.Copy(out, in); err != nil {
		out.Close()
		return err
	}
	return out.Close()
}

func oneLine(value string) string {
	return strings.Join(strings.Fields(strings.ReplaceAll(value, "\n", " ")), " ")
}
