// Package packager builds .pkg.tar.zst archives without makepkg. It is used
// on systems where the Arch build tools are unavailable or the root
// filesystem is read-only (SteamOS, live images, containers).
package packager

import (
	"archive/tar"
	"compress/gzip"
	"crypto/md5"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/klauspost/compress/zstd"

	"github.com/Serge-Nook/kuznica/internal/pkgbuild"
)

// Builder describes a single package build.
type Builder struct {
	Spec       pkgbuild.Spec
	PayloadDir string // directory whose contents become the package root
	Install    string // optional .INSTALL hook contents
	OutputDir  string
	BuildDate  time.Time
}

// entry is a payload member collected before writing the archive.
type entry struct {
	path     string // path relative to PayloadDir, slash separated
	info     os.FileInfo
	linkName string
}

// Build writes the package archive and returns its path.
func (b Builder) Build() (string, error) {
	entries, installed, err := collect(b.PayloadDir)
	if err != nil {
		return "", err
	}
	if b.BuildDate.IsZero() {
		b.BuildDate = time.Now()
	}

	name := fmt.Sprintf("%s-%s-%s-%s.pkg.tar.zst",
		pkgbuild.SanitizeName(b.Spec.PkgName),
		pkgbuild.SanitizeVersion(b.Spec.PkgVersion),
		release(b.Spec.PkgRelease),
		archName(b.Spec.Arch),
	)
	target := filepath.Join(b.OutputDir, name)

	file, err := os.Create(target)
	if err != nil {
		return "", err
	}
	defer file.Close()

	encoder, err := zstd.NewWriter(file, zstd.WithEncoderLevel(zstd.SpeedDefault))
	if err != nil {
		return "", err
	}
	archive := tar.NewWriter(encoder)

	mtree, err := renderMTree(b.PayloadDir, entries)
	if err != nil {
		return "", err
	}

	metadata := []struct {
		name string
		body []byte
		mode int64
	}{
		{".PKGINFO", []byte(b.renderPKGINFO(installed)), 0o644},
		{".MTREE", mtree, 0o644},
	}
	if strings.TrimSpace(b.Install) != "" {
		metadata = append(metadata, struct {
			name string
			body []byte
			mode int64
		}{".INSTALL", []byte(b.Install), 0o644})
	}
	for _, item := range metadata {
		header := &tar.Header{
			Name:     item.name,
			Mode:     item.mode,
			Size:     int64(len(item.body)),
			ModTime:  b.BuildDate,
			Uname:    "root",
			Gname:    "root",
			Typeflag: tar.TypeReg,
		}
		if err := archive.WriteHeader(header); err != nil {
			return "", err
		}
		if _, err := archive.Write(item.body); err != nil {
			return "", err
		}
	}

	for _, item := range entries {
		if err := writeEntry(archive, b.PayloadDir, item); err != nil {
			return "", err
		}
	}

	if err := archive.Close(); err != nil {
		return "", err
	}
	if err := encoder.Close(); err != nil {
		return "", err
	}
	return target, nil
}

// collect walks the payload and returns its members plus the installed size.
func collect(root string) ([]entry, int64, error) {
	info, err := os.Stat(root)
	if err != nil {
		return nil, 0, fmt.Errorf("payload directory: %w", err)
	}
	if !info.IsDir() {
		return nil, 0, fmt.Errorf("payload %s is not a directory", root)
	}

	var (
		entries   []entry
		installed int64
	)
	err = filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if path == root {
			return nil
		}
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		item := entry{path: filepath.ToSlash(relative), info: info}
		if info.Mode()&os.ModeSymlink != 0 {
			if item.linkName, err = os.Readlink(path); err != nil {
				return err
			}
		} else if info.Mode().IsRegular() {
			installed += info.Size()
		} else if !info.IsDir() {
			return nil // sockets and devices are not packaged
		}
		entries = append(entries, item)
		return nil
	})
	if err != nil {
		return nil, 0, err
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].path < entries[j].path })
	return entries, installed, nil
}

func writeEntry(archive *tar.Writer, root string, item entry) error {
	header, err := tar.FileInfoHeader(item.info, item.linkName)
	if err != nil {
		return err
	}
	header.Name = item.path
	if item.info.IsDir() {
		header.Name += "/"
	}
	// Ownership is normalised instead of relying on fakeroot.
	header.Uid, header.Gid = 0, 0
	header.Uname, header.Gname = "root", "root"

	if err := archive.WriteHeader(header); err != nil {
		return err
	}
	if !item.info.Mode().IsRegular() {
		return nil
	}
	file, err := os.Open(filepath.Join(root, filepath.FromSlash(item.path)))
	if err != nil {
		return err
	}
	defer file.Close()
	_, err = io.Copy(archive, file)
	return err
}

func (b Builder) renderPKGINFO(installed int64) string {
	name := pkgbuild.SanitizeName(b.Spec.PkgName)
	var sb strings.Builder
	sb.WriteString("# Generated by KUZNICA (https://sd-on.ru)\n")
	fmt.Fprintf(&sb, "pkgname = %s\n", name)
	fmt.Fprintf(&sb, "pkgbase = %s\n", name)
	fmt.Fprintf(&sb, "pkgver = %s-%s\n", pkgbuild.SanitizeVersion(b.Spec.PkgVersion), release(b.Spec.PkgRelease))
	fmt.Fprintf(&sb, "pkgdesc = %s\n", oneLine(b.Spec.PkgDesc))
	if b.Spec.URL != "" {
		fmt.Fprintf(&sb, "url = %s\n", b.Spec.URL)
	}
	fmt.Fprintf(&sb, "builddate = %d\n", b.BuildDate.Unix())
	fmt.Fprintf(&sb, "packager = %s\n", packager(b.Spec.Maintainer))
	fmt.Fprintf(&sb, "size = %d\n", installed)
	fmt.Fprintf(&sb, "arch = %s\n", archName(b.Spec.Arch))
	for _, license := range defaults(b.Spec.License, []string{"custom"}) {
		fmt.Fprintf(&sb, "license = %s\n", license)
	}
	writeList(&sb, "depend", b.Spec.Depends)
	writeList(&sb, "optdepend", b.Spec.OptDepends)
	writeList(&sb, "conflict", b.Spec.Conflicts)
	writeList(&sb, "provides", b.Spec.Provides)
	writeList(&sb, "replaces", b.Spec.Replaces)
	return sb.String()
}

// renderMTree produces the gzip compressed .MTREE index pacman uses to
// verify installed files.
func renderMTree(root string, entries []entry) ([]byte, error) {
	var text strings.Builder
	text.WriteString("#mtree\n")
	text.WriteString("/set type=file uid=0 gid=0 mode=644\n")
	for _, item := range entries {
		mode := fmt.Sprintf("%o", item.info.Mode().Perm())
		fmt.Fprintf(&text, "./%s", escapeMTree(item.path))
		switch {
		case item.info.IsDir():
			fmt.Fprintf(&text, " type=dir mode=%s time=%d.0\n", mode, item.info.ModTime().Unix())
		case item.linkName != "":
			fmt.Fprintf(&text, " type=link link=%s time=%d.0\n", escapeMTree(item.linkName), item.info.ModTime().Unix())
		default:
			md5sum, sha, err := digests(filepath.Join(root, filepath.FromSlash(item.path)))
			if err != nil {
				return nil, err
			}
			fmt.Fprintf(&text, " time=%d.0 mode=%s size=%d md5digest=%s sha256digest=%s\n",
				item.info.ModTime().Unix(), mode, item.info.Size(), md5sum, sha)
		}
	}

	var buffer strings.Builder
	writer := gzip.NewWriter(&buffer)
	if _, err := io.WriteString(writer, text.String()); err != nil {
		return nil, err
	}
	if err := writer.Close(); err != nil {
		return nil, err
	}
	return []byte(buffer.String()), nil
}

func digests(path string) (string, string, error) {
	file, err := os.Open(path)
	if err != nil {
		return "", "", err
	}
	defer file.Close()

	md5sum := md5.New()
	sha := sha256.New()
	if _, err := io.Copy(io.MultiWriter(md5sum, sha), file); err != nil {
		return "", "", err
	}
	return hex.EncodeToString(md5sum.Sum(nil)), hex.EncodeToString(sha.Sum(nil)), nil
}

// escapeMTree encodes the characters mtree treats as separators.
func escapeMTree(value string) string {
	replacer := strings.NewReplacer(
		`\`, `\\`,
		" ", `\040`,
		"\t", `\011`,
		"#", `\043`,
		"=", `\075`,
	)
	return replacer.Replace(value)
}

func writeList(sb *strings.Builder, key string, values []string) {
	for _, value := range values {
		if strings.TrimSpace(value) == "" {
			continue
		}
		fmt.Fprintf(sb, "%s = %s\n", key, value)
	}
}

func release(value string) string {
	if strings.TrimSpace(value) == "" {
		return "1"
	}
	return value
}

func archName(arch []string) string {
	if len(arch) == 0 {
		return "any"
	}
	return arch[0]
}

func packager(maintainer string) string {
	if strings.TrimSpace(maintainer) == "" {
		return "KUZNICA <https://sd-on.ru>"
	}
	return oneLine(maintainer)
}

func oneLine(value string) string {
	return strings.Join(strings.Fields(strings.ReplaceAll(value, "\n", " ")), " ")
}

func defaults(values, fallback []string) []string {
	if len(values) == 0 {
		return fallback
	}
	return values
}
